# Generated by Django 5.2.4 on 2025-08-15 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_alter_customer_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='totalAmount',
            new_name='total_amount',
        ),
    ]
